image: docker:stable
services:
  - docker:stable-dind

variables:
  CATALOGUE_NAME: microbe
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG

workflow:
  rules:
    - when: always

stages:
  - build
  - publish

build:
  stage: build
  tags:
    - dind
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .

publish:
  stage: publish
  script:
    - set | grep CI_REGISTRY
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
